# Generated by Django 5.1.6 on 2025-03-10 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_servicio_total_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='numero_cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='total_general',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='total_servicio',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_cotizacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.catalogoservicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.catalogoservicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogoservicio',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.vehiculo'),
        ),
    ]
