# Generated by Django 5.1.6 on 2025-03-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_catalogoservicio_cotizacion_detallecotizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='venta',
        ),
    ]
