# Generated by Django 5.1.6 on 2025-03-10 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_cotizacion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.vehiculo'),
        ),
    ]
