# Generated by Django 5.1.6 on 2025-03-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_producto_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
