# Generated by Django 4.2.5 on 2025-03-13 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_catalogoservicio_servicio_venta_moduloreparacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduloreparacion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='moduloreparacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduloreparacion',
            name='fecha_reparacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='moduloreparacion',
            name='numero_parte',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='moduloreparacion',
            name='precio_reparacion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
