# Generated by Django 5.1.6 on 2025-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_moduloreparacion_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
