# Generated by Django 5.1.6 on 2025-03-10 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_cotizacion_fecha_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_cotizacion',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
