# Generated by Django 5.1.6 on 2025-03-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_detalleproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='crm.cotizacion'),
        ),
    ]
