# Generated by Django 5.1.6 on 2025-03-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_detalleservicio_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.catalogoservicio'),
        ),
    ]
