# Generated by Django 5.1.6 on 2025-03-12 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_servicio_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.catalogoservicio'),
            preserve_default=False,
        ),
    ]
